.before_script_template: &ubuntu_before_script
  image: ubuntu:rolling
  before_script:
    - apt-get update
    - apt-get install -q -y --no-install-recommends valac gcc gettext itstool libgtk-3-dev libgtk-3-bin libgtksourceview-4-dev libmpc-dev libmpfr-dev libsoup2.4-dev libxml2-dev libgee-0.8-dev libvala-0.48 python3-pip ninja-build
    - pip3 install --upgrade setuptools
    - pip3 install --no-cache-dir meson>=0.50.0

.before_script_template: &fedora_before_script
  image: fedora:latest
  before_script:
    - dnf install -y meson vala itstool gtk3-devel gtksourceview4-devel libmpc-devel mpfr-devel libsoup-devel libxml2-devel libgee-devel

.build_template: &meson_build
  stage: build
  script:
    - meson -Dui-tests=true _build .
    - ninja -C _build install
  artifacts:
    paths:
      - _build/
    expire_in: 2 hours

.test_template: &meson_test
  stage: test
  script:
    - broadwayd &
    - GDK_BACKEND=broadway ninja -C _build test

build:fedora:
  <<: *fedora_before_script
  <<: *meson_build

build:ubuntu:
  <<: *ubuntu_before_script
  <<: *meson_build

build:snap:
  stage: build
  image: ubuntudesktop/gnome-3-28-1804
  before_script:
    - apt-get update
  script: snapcraft
  allow_failure: true
  artifacts:
    paths: ['./*.snap']
    expire_in: 3 days

test:ubuntu:
  dependencies:
    - build:ubuntu
  <<: *ubuntu_before_script
  <<: *meson_test

test:fedora:
  dependencies:
    - build:fedora
  <<: *fedora_before_script
  <<: *meson_test

include: 'https://gitlab.gnome.org/GNOME/citemplates/raw/master/flatpak/flatpak_ci_initiative.yml'

variables:
    BUNDLE: "gnome-calculator-dev.flatpak"

flatpak:
    image: 'registry.gitlab.gnome.org/gnome/gnome-runtime-images/gnome:master'
    variables:
        MANIFEST_PATH: "org.gnome.Calculator.json"
        FLATPAK_MODULE: "gnome-calculator"
        RUNTIME_REPO: "https://sdk.gnome.org/gnome-nightly.flatpakrepo"
        APP_ID: "org.gnome.Calculator"
    extends: .flatpak

review:
    stage: deploy
    dependencies:
        - 'flatpak'
    extends: '.review'

stop_review:
    stage: deploy
    extends: '.stop_review'

